name: Testapalooza

on: pull_request

jobs:

  build:
    strategy:
        matrix:
          os: [ubuntu-latest]
          golang: [1.17]

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
        id: go

      - name: Install Subo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo clone suborbital/subo
          cd subo
          gh pr checkout 116
          make subo
          cd ../
          rm -rf subo

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod download

      - name: Build testdata
        run: |
          make testdata/docker/dev
        
        # Test first with default (Wasmer) runtime, and then again with Wasmtime runtime
      - name: Run test
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          go test -v ./...
      
      - name: Run test with Wasmtime
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          go test -v --tags wasmtime ./...
